# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-hjPzJ3h0OpeYX0ZtDy2U-baF_0X_CX
"""

import pandas as pd

df = pd.read_csv("../data/sales_data_usd.csv")
print(df.describe())